name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Setup Clojure CLI
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: latest
    - name: Cache .m2
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Cache .gitlibs
      uses: actions/cache@v1
      with:
        path: ~/.gitlibs
        key: ${{ runner.os }}-gitlibs-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-gitlibs-
    - name: Cache .cpcache
      uses: actions/cache@v1
      with:
        path: .cpcache
        key: ${{ runner.os }}-cpcache-${{ hashFiles('deps.edn') }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install deps
      run: |
        clojure -Rcheck:test:cljs:coverage -Stree
        npm install
    - name: Run check
      run: clojure -Acheck
    - name: Run CLJ tests
      run: clojure -Atest
    - name: Run CLJS tests on Node
      run: clojure -Atest:cljs:test-cljs
    - name: Run CLJS tests on browser
      run: |
        npx shadow-cljs compile test
        npx karma start --single-run
    - name: Run CLJS tests (advanced build) on browser
      run: |
        npx shadow-cljs release test
        npx karma start --single-run
    - name: Measure test coverage
      run: clojure -Atest:coverage
    - name: Upload coverage report to CodeCov
      uses: codecov/codecov-action@v1
