name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Setup Clojure CLI
      uses: DeLaGuardo/setup-clojure@3.1
      with:
        tools-deps: latest
    - name: Cache deps
      uses: actions/cache@v1
      with:
        path: |
          ~/.m2
          ~/.gitlibs
          .cpcache
        key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-deps-
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install deps
      run: |
        clojure -A:check:test:cljs:coverage -P
        npm install
    - name: Run check
      run: clojure -M:check
    - name: Run CLJ tests
      run: clojure -M:test
    - name: Run CLJS tests on Node
      run: clojure -M:test:cljs:test-cljs
    - name: Run CLJS tests on browser
      run: |
        npx shadow-cljs compile test
        npx karma start --single-run
    - name: Run CLJS tests (advanced build) on browser
      run: |
        npx shadow-cljs release test
        npx karma start --single-run
    - name: Measure test coverage
      run: clojure -M:test:coverage
    - name: Upload coverage report to CodeCov
      uses: codecov/codecov-action@v1
